image: Visual Studio 2017
configuration: Release

before_build:
  - nuget restore
  
build_script: 
 - msbuild "Google Drive Uploader1.sln" /p:TargetFrameworkVersion=v4.7.2

artifacts:
 - path: '*\bin\Release\*.exe'
