image: Visual Studio 2019
configuration: Release

before_build:
  - ps: mkdir "Google Drive Uploader1\bin\Release"
  - ps: Start-FileDownload https://moisescardona.me/files/SoftwareDependencies/GoogleDriveUploadTool/MemoryTributary.dll -f "C:\projects\googledriveuploadtool\Google Drive Uploader1\bin\Release\MemoryTributary.dll"
  - nuget restore
  
build_script: 
 - msbuild "Google Drive Uploader1.sln" /p:TargetFrameworkVersion=v4.8

artifacts:
 - path: '*\bin\Release\*.exe'
